### ISSUE TITLE
Inconsistent responses JSON

### ISSUE THREAD

**Issue by izxxr** [PGamerXstudio/blacksheep#25]
The problem that I have run into while using API is inconsistency of responses. By that I mean, That responses are not consistent. For an instance, This is the response JSON on normal AI response:
```py
[{"message": "response"}, {"response_time"}: "Normal"]
```
Even though this should be a simple JSON without arrays but okay, But why does ratelimit JSON look like this:
```json
["Ratelimit warning message"]
```
Why can't it be:
```json
[{"message": "Ratelimit Warning"}]
```
Or better way,
```json
{
  "message": "Ratelimit warning",
  "response_time": "normal"
}
```
This was just AI endpoint there can be improvements on other endpoints too (Making all responses similar and organised). So, It's easy for developers to make wrappers as well as users to use the API.

**Comment by sachin-sankar** [comment]
# Use status codes
That is better.

**Comment by pgamerx** [comment]
> The problem that I have run into while using API is inconsistency of responses. By that I mean, That responses are not consistent. For an instance, This is the response JSON on normal AI response:
> 
> ```python
> [{"message": "response"}, {"response_time"}: "Normal"]
> ```
> 
> Even though this should be a simple JSON without arrays but okay, But why does ratelimit JSON look like this:
> 
> ```json
> ["Ratelimit warning message"]
> ```
> 
> Why can't it be:
> 
> ```json
> [{"message": "Ratelimit Warning"}]
> ```
> 
> Or better way,
> 
> ```json
> {
>   "message": "Ratelimit warning",
>   "response_time": "normal"
> }
> ```
> 
> This was just AI endpoint there can be improvements on other endpoints too (Making all responses similar and organised). So, It's easy for developers to make wrappers as well as users to use the API.

Don't want to edit v4 response by any chance now because everyone is already using that.
v5 will be good!

**Comment by izxxr** [comment]
Gotcha
