### ISSUE TITLE
Improve Response Headers

### ISSUE THREAD

**Issue by sachin-sankar** [PGamerXstudio/blacksheep#26]
#### Currently there is nothing useful sent with the response in the headers instead on each response the API should return the `requests-remaining` with the remaining request quota for that api key.

**Comment by izxxr** [comment]
...And on ratelimits, It should return `try-again-in` with the time we can try again.

**Comment by sachin-sankar** [comment]
> ...And on ratelimits, It should return `try-again-in` with the time we can try again.

Also the time should be `epoch` seconds for compatibility.

**Comment by izxxr** [comment]
> > ...And on ratelimits, It should return `try-again-in` with the time we can try again.
> 
> Also the time should be `epoch` seconds for compatibility.

Indeed! 👍🏻

**Comment by pgamerx** [comment]
Won't work on anything right now, sorry
My first aim is to make the code transparent.
I am hiding all the imp stuff which can lead to data leak. 
Then i will open source the api
