### ISSUE TITLE
RSA few odd responses

### ISSUE THREAD

**Issue by muzak23** [PGamerXstudio/blacksheep#29]
'007' responseds with an extra <br /> https://canary.discord.com/channels/690557545965813770/800261406947541002/865599203358146581

'E6 2B 88 32 0F BE' gets a weird Chinese response translating to "Is it rude to say that?" https://canary.discord.com/channels/690557545965813770/800261406947541002/865599090565316668

**Comment by pgamerx** [comment]
Will be fixed in next update along with introduction to flags...
