### ISSUE TITLE
API Key is invalid!

### ISSUE THREAD

**Issue by ghost** [PGamerXstudio/blacksheep#30]
The API Key is always invalid!
I regenerated it again and again but doesn't work!

**Comment by pgamerx** [comment]
> The API Key is always invalid!
> I regenerated it again and again but doesn't work!

Can you contact me on [Discord](https://u.pgamerx.com/discord)
I can confirm your API key is working but looks like you are entering a wrong one. 
Just a reminder - Your API key is case-sensitive

**Comment by ghost** [comment]
I know i's case-sensitive. The BOT DM'd me the API Key and I simply copy-pasted it!

It always shows the error 'API Key is Invalid'

**Comment by pgamerx** [comment]
> I know i's case-sensitive. The BOT DM'd me the API Key and I simply copy-pasted it!

The bot dmed you 2 keys. 
Are you sure you didn't use of the 2nd one because that's supposed to be your ID and not api key

**Comment by ghost** [comment]
I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?

**Comment by pgamerx** [comment]
> I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?

No, do me a favour. 
Visit [Dashboard](https://dash.pgamerx.com) 
Login with Discord/Google and then head over to profile.
Copy and paste the API key from there

**Comment by ghost** [comment]
> > I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?
> 
> No, do me a favour.
> Visit [Dashboard](https://dash.pgamerx.com)
> Login with Discord/Google and then head over to profile.
> Copy and paste the API key from there

I finished this process and copy-pasted the API Key into my program

**Comment by pgamerx** [comment]
> > > I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?
> > 
> > 
> > No, do me a favour.
> > Visit [Dashboard](https://dash.pgamerx.com)
> > Login with Discord/Google and then head over to profile.
> > Copy and paste the API key from there
> 
> I finished this process and copy-pasted the API Key into my program

and did it work?....

**Comment by ghost** [comment]
> > > > I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?
> > > 
> > > 
> > > No, do me a favour.
> > > Visit [Dashboard](https://dash.pgamerx.com)
> > > Login with Discord/Google and then head over to profile.
> > > Copy and paste the API key from there
> > 
> > 
> > I finished this process and copy-pasted the API Key into my program
> 
> and did it work?....

It didn't that's why I opened this issue!

**Comment by pgamerx** [comment]
> > > > > I know the second one's not mine. Can I send a screenshot of the API Key here? Is it fine?
> > > > 
> > > > 
> > > > No, do me a favour.
> > > > Visit [Dashboard](https://dash.pgamerx.com)
> > > > Login with Discord/Google and then head over to profile.
> > > > Copy and paste the API key from there
> > > 
> > > 
> > > I finished this process and copy-pasted the API Key into my program
> > 
> > 
> > and did it work?....
> 
> It didn't that's why I opened this issue!

Excuse me sir, DId you go to the dashboard as I asked?
Because I logged in with your credentials and it works for me
Which means your api key is correct. Kindly check it again
Your credentials means
Email : Your email
Password: Your api key
![Screenshot 2021-08-27 at 5 26 55 PM](https://user-images.githubusercontent.com/71639879/131123882-61994840-e05f-4119-9a0d-50c8865c72b7.png)

**Comment by ghost** [comment]
I'll try again then!

**Comment by ghost** [comment]
Ok, it worked this time! Thanks for your support!
